import numpy as np
import PatternToNumber 

def computing_frequencies(text, k):
	m = 4**k  
	frequency_array = np.zeros(shape = (1, m), dtype = int)
	
	for i in range(len(text) - k + 1):
		pattern = text[i:i+k]
		j = PatternToNumber.pattern_to_number(pattern)
		frequency_array[0 , j] = frequency_array[0, j] + 1
	return frequency_array

def results(text, t):
	result = computing_frequencies(text, t).tolist()
	for line in result:
		print(' '.join(map(str, line)))

results('GAGCGGGACACGTATTATAACGAAGAAAACGGGAGACTAAACTGTAGAGGACTCTTGCCAGCATACGTAACAAGCTCGACGCAGCGCGTAGTCTGATCCGAGTGAATCCGATCCCAGCAAAGGTCGTGGTTGTGTTCGGGGGGGCCTCGCGGGGGCTGCGGACTACCCTCTTGCGCCTAAGCATAAGCTCAGGAACCTGTTTCTTATGCAATTCTGTTAAGACCTTCCAAACGCATAAGGGCTCTGATTGCTAGTATGATAGAACAATCCGCACCCACCAGCTAATAGGAAGCCAACATAGCGGAGGGACACGGCTGCCTAGCCAGGACAACATTCGAGTATGATCAGAGTGCACCGGAATAGGATACTCGTGGTCGCAACGTCGCACGGCTTTCCTAAGCTGTGGAAAAGATTCAACGGACTCAGCGCCAGCGCCCGGGGACCACCGTATCTATGGGGAGTCAGTGAGAGCAGAGCAGTTGGGGGAAAAACAGCGATCCTGGCGGACACCGAGAGTTCGCATTGTATATGAAGTAGCAGCGAGTAGAGTAGATTACTGATCGAATGGTCGCGTGATCCCTGGCAAATCCTACAAAATAGGAGGAGCTGAGGCGCTCGGCCCCGATCCTGGTTTTTCTGACCCGCA', 5)		


